### ISSUE TITLE
Unit test not working fine

### ISSUE THREAD

**Issue by AMBTIONGP** [fevziomurtekin/DeezerClone#30] opened 2021-06-05 23:44 UTC
Unit test not working fine more details on this question 
https://stackoverflow.com/questions/67845727/test-classes-doesnt-work-correctly-on-android

**Comment by fevziomurtekin** [comment] 2021-06-06 12:51
Hey @AMBTIONGP ! Thanks for share this error with me. 

I  made some changes on unit test classes. Please, check the changes on Master branch. ✌🏻

**Comment by AMBTIONGP** [comment] 2021-06-06 17:11
I deleted my cloned repository and clone it again and tried to change these methods to be like that 

In DeezerServiceTest
```
    @Throws(IOException::class)
    @Test
    fun fetchArtistList(): Unit = runBlocking {
        enqueueResponse("/artistsResponse.json")
        // give to default genreID
        val response = service.fetchArtistList(MockUtil.genreID)
        mockWebServer.takeRequest()

        client.fetchArtistList(MockUtil.genreID)

        response?.body()?.artistData?.let { safeList ->
            assertThat("safeList[0].id", `is`("8354140"))
        }

    }
```
```
In ArtistRepositoryTest 
  @ExperimentalTime
  @Test
  fun fetchArtistListFromNetworkTest() = runBlocking {
    val mockData = ArtistsResponse(listOf(MockUtil.artist))
    val returnData = Response.success(mockData)
    whenever(service.fetchArtistList(MockUtil.genreID)).thenReturn(returnData)

    repository.fetchArtistList(MockUtil.genreID).test {
      val result = expectItem()
      assertEquals(result, ApiResult.Success(listOf(MockUtil.artist)))
      Assert.assertEquals((result as ApiResult.Success<List<ArtistData>>).data[0].name , "Ezhel")
      Assert.assertEquals("result.data[0].id" , "8354140")
      expectComplete()
    }

    verify(service, atLeastOnce()).fetchArtistList(MockUtil.genreID)
    verifyNoMoreInteractions(service)
  }
```

and it stills passed 

is there any custom choice about configuration because in first try to test it asked me about configuration and I choose [this ]([url](https://ibb.co/JycxdCh)) Jar Manifest

**Comment by fevziomurtekin** [comment] 2021-06-06 18:15
Please pull master branch then try again 👍🏻

**Comment by AMBTIONGP** [comment] 2021-06-06 20:47
> 
> 
> Please pull master branch then try again 👍🏻

I do and it stills have a problem here a full record of the test process  https://we.tl/t-XJhzgZUOV3

**Comment by AMBTIONGP** [comment] 2021-06-08 12:37
@fevziomurtekin  update I make more debugs to detect what's the problem exactly and it was in the MainCoroutineRule because I add seperate new method  
```
@Test
    fun addition_isCorrect() {
        assertEquals(4, 3 + 2)
    }
```
and it didn't fail until I comment the variables and method for setup the test for example I commented these parts in DeezerServiceTest to able to see method  (addition_isCorrect) fails 

        ```
    //private lateinit var service: DeezerService

            //@MockK
            //private lateinit var client: DeezerClient

           // @ExperimentalCoroutinesApi
           // @get:Rule 
            //var coroutineRule = MainCoroutineRule()

      
           // @Before
           // fun initService(){
            //    MockKAnnotations.init(this, relaxed = true)
           //     service = createService(DeezerService::class.java)
            //    client = DeezerClient(service)
          //  }
```

**Comment by fevziomurtekin** [comment] 2021-06-09 07:17
Hey! @AMBTIONGP 
I deleted the project and clone it again.

The result is the same. "Tests passed: 31 of 31 tests". You can see ![Screen Shot](https://user-images.githubusercontent.com/12996047/121310140-b72dfe00-c90b-11eb-9760-1acf0d89a613.png)

Your machine jvm may have a problem .

If you can write the error in logcat, maybe we can find it. But the problem is not code.

**Comment by AMBTIONGP** [comment] 2021-06-09 13:55
I fix that using [that answer ](https://stackoverflow.com/a/59649406/4979652) and still had a problem 

![Untitled](https://user-images.githubusercontent.com/85419631/121367140-58cc4400-c93a-11eb-8789-fc76d8b88a16.png)

In the next image roboelectic warn gone but the tests still passed for example in the DeezerServiceTest I added this function 

```
 @Test
    fun assertTester(){
        assertEquals(1,2)
    }
```
And it passed also 

![tester](https://user-images.githubusercontent.com/85419631/121367148-59fd7100-c93a-11eb-8f58-87db5abeaf4b.png)

**Comment by fevziomurtekin** [comment] 2021-06-09 14:20
Hmm.. As I said, it was caused by the machine. But if the problem is solved, it's fine. I am happy for you 🚀

**Comment by AMBTIONGP** [comment] 2021-06-09 14:51
> 
> 
> Hmm.. As I said, it was caused by the machine. But if the problem is solved, it's fine. I am happy for you 🚀

@fevziomurtekin  I changed my JRE to 9 but nothing changes how it was in JVM, isn't method assertTester supposed to fail 

```
 @Test
    fun assertTester(){
        assertEquals(1,2)
    }
```

**Comment by fevziomurtekin** [comment] 2021-06-09 15:02
1 and 2 are equal? Sure that, should be failed.

**Comment by fevziomurtekin** [comment] 2021-06-09 15:05
I'll close the issue.

**Comment by AMBTIONGP** [comment] 2021-06-09 15:17
@fevziomurtekin assertTester functions fails only if I comment the initservice function and variables as mentioned in this comment https://github.com/fevziomurtekin/DeezerClone/issues/30#issuecomment-856728987 so If the clase goes inside MainCoroutineRule it makes all test inside it passed even if it has false assertions but if I comment them and run the class it works perfectly as it supposed if the assertion false the test fails and else it passed  

By the way I run the tests on two devices and it has the same problem test always passed even if it has the false assertions

**Closed** 2021-06-09 15:29 UTC
